/**
 * @author Miller Zhao
 * @date 2021-03-24
 * @description This class is used to store picklist values.
 */
public class JK_PicklistConstant {
    public JK_PicklistConstant() { }

    //Destination Country 
    public static final String AUSTRALIA = 'Australia';

    //Region
    public static final String EU_Union = 'EU(Union)';
    public static final String EU_NonEu = 'EU(Non-Eu)';
    public static final String ROA = 'ROA';
    public static final String NORTHASIA = 'North Asia';
    public static final String SOUTHASIA = 'South Asia';
    public static final String NORTHAMERICA = 'North America';
    public static final String MEA = 'Middle East&Africa';
    public static final String LAI = 'Latin America&Italy';
    public static final String KEYACCOUNT = 'Key Account';
    public static final String CENTRALASIA = 'Central Asia';
    public static final String CN = 'CN';
    public static final String SSA = 'SSA';
    public static final String MENA = 'MENA';
}
