@istest
public class paymentVCctrlTest {
    static testMethod void myTest(){
        paymentVCctrl pvc =new paymentVCctrl();
        pvc.requestId='800';
         pvc.requestId2='800';
         pvc.requestId3='800';
        pvc.requestId4='800';
         pvc.requestId5='800';
         pvc.requestId6='800';
         pvc.requestId7='800';
        paymentVCctrl2 pvc2 =new paymentVCctrl2();
        pvc2.requestId='006';
        pvc2.requestId2='006';
        pvc2.requestId3='006';
        pvc2.requestId4='006';
        pvc2.requestId5='006';
        pvc2.requestId6='006';
        pvc2.requestId7='006';
    }
}