@isTest
private class sapDeliveryTest {
    
	
    static testMethod void myUnitTest() {
    	sapDelivery.ZSDO0054_element zsdele = new sapDelivery.ZSDO0054_element();
    	sapDelivery.ZSDO0054Response_element zsdresele = new sapDelivery.ZSDO0054Response_element();
    	sapDelivery.TABLE_OF_ZSDO0054 zsdo = new sapDelivery.TABLE_OF_ZSDO0054();
    	sapDelivery.ZSDO0054 zsd = new sapDelivery.ZSDO0054();
    	sapDelivery.ZSDO0054 tool = new sapDelivery.ZSDO0054();
    	//tool.ZSDO0054A(zsdo,'');
    }

}